project_id = "gtmsjqqqzsfganppcdxe"

[functions.generate-career-recommendation]
verify_jwt = false

[functions.track-upsell-click]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.createPreference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.verify-mp-payment]
verify_jwt = false

[functions.check-mp-credentials]
verify_jwt = true

[functions.list-orders]
verify_jwt = true

[functions.list-users]
verify_jwt = true